name: CI/CD

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # â€”â€” Setup Github Actions ğŸ™ â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”
      - uses: actions/checkout@master

      # â€”â€” Setup node ğŸ‹ â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”
      - name: Setup NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: "12.16.2"

      - name: Install Dependencies
        run: npm install

      - name: Install ci
        run: npm ci
    - run: npm run build --if-present
    - run: npm npm run test:unit
      env:
        CI: true
    - run: npm npm run e2e
      env:
        CI: true
