name: CI/CD

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # â€”â€” Setup Github Actions ğŸ™ â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”
      - uses: actions/checkout@master

      # â€”â€” Setup node ğŸ‹ â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”
      - name: Setup NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: "12.16.2"

      - name: Install Dependencies
        run: npm install

      - name: Install ci
        run: npm ci

      # â€”â€” Tests âœ… â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”
      - name: Run unit tests
        with:
          build: npm run build
          start: CI=true npm run test:unit

        # run: CI=true npm run test:unit
      - name: Run e2e tests
        with:
          build: npm run build
          start: CI=true npm run e2e
          wait-on: http://localhost:9515
        # run: CI=true npm run e2e
